# Uncomment the next line to define a global platform for your project
platform :ios, '13.0'

source 'https://github.com/CocoaPods/Specs.git'

target 'Sample_SDK' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
#  pod 'LensSDK', :git => 'https://github.com/zoho/LensCustomerSDK.git', :tag => '2.4.3-beta'
  pod 'LensSDK', :path => '../LensSDK.podspec'
  
  post_install do |installer|
    
    installer.generated_projects.each do |project|
          project.targets.each do |target|
              target.build_configurations.each do |config|
                  config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '11.0'
               end
          end
   end
    installer.pods_project.targets.each do |target|
      if target.name["LensSDK"] || target.name["GoogleWebRTC"]
        target.build_configurations.each do |config|
          config.build_settings['ENABLE_BITCODE'] = 'NO'
        end
      end
      installer.pods_project.targets.each do |target|
        target.build_configurations.each do |config|
          config.build_settings['BUILD_LIBRARY_FOR_DISTRIBUTION'] = 'YES'
        end
      end
    end
  end
end

