# Uncomment the next line to define a global platform for your project
 platform :ios, '11.0'

target 'Sample_SDK' do
  # Comment the next line if you don't want to use dynamic frameworks
   use_frameworks!
#   pod "LensSDK", :git => 'https://github.com/zoho/LensCustomerSDK.git'
  pod "LensSDK", :podspec => '../LensSDK.podspec'

  post_install do |installer|
    installer.pods_project.targets.each do |target|
      if target.name["LensSDK"] || target.name["GoogleWebRTC"]
        target.build_configurations.each do |config|
          config.build_settings['ENABLE_BITCODE'] = 'NO'
        end
      end
    end
  end
end
